### ISSUE TITLE
Sometimes enemy trinket has no icon texture.

### ISSUE THREAD

**Issue by Kazimazi** [Qblolz/sArena-wotlk-classic#2]

**Comment by Qblolz** [comment]
Any skins addon ? That doing recolor some elements ?

**Comment by Kazimazi** [comment]
nope, nothing like that

**Comment by Qblolz** [comment]
I need more details about this cuz I using own addons every day and never seen this bug
For better reaction - wisp in discord Qb#6652 if u understand how to reproduce errors

**Comment by Kazimazi** [comment]
sure thing, will hit you up on discord tomorrow

**Comment by Qblolz** [comment]
fixed
